version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_NAME=“imageapi”
      - REPOSITORY_URI_CLIENT1=135487423365.dkr.ecr.ap-northeast-2.amazonaws.com/client
      - REPOSITORY_URI_CLIENT2=135487423365.dkr.ecr.ap-northeast-2.amazonaws.com/client
      - REPOSITORY_URI_CLIENT3=135487423365.dkr.ecr.ap-northeast-2.amazonaws.com/client
      - IMAGE_TAG=prod_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Image_tag $IMAGE_TAG
      - docker build -t $REPOSITORY_URI_CLIENT1:latest ./client
      - docker build -t $REPOSITORY_URI_CLIENT2:latest ./client2
      - docker build -t $REPOSITORY_URI_CLIENT3:latest ./client3
      - docker tag $REPOSITORY_URI_CLIENT1:latest $REPOSITORY_URI_CLIENT1/client:$IMAGE_TAG
      - docker tag $REPOSITORY_URI_CLIENT2:latest $REPOSITORY_URI_CLIENT2/client2:$IMAGE_TAG
      - docker tag $REPOSITORY_URI_CLIENT3:latest $REPOSITORY_URI_CLIENT3/client3:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_CLIENT1/client:$IMAGE_TAG
      - docker push $REPOSITORY_URI_CLIENT2/client2:$IMAGE_TAG
      - docker push $REPOSITORY_URI_CLIENT3/client3:$IMAGE_TAG
